name: Deploy to EC2

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and deploy
      run: |
        cd ~
        ls
        cd aws-ec2-telegram-bot-helper/SelfEduMain
        source venv/bin/activate
        git pull
        pkill -f Telegram/goofy_helper_bot.py
        python3 Telegram/goofy_helper_bot.py

