name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
#       git pull origin master
        pkill -f Telegram/goofy_helper_bot.py
        python3 Telegram/goofy_helper_bot.py

